uploading recent changes to make sure everybody is on the same page; …
raynhlee/grace-shopper-capstone pull request #29
Opened 2023-06-30 05:05 UTC by shruthi-tuplur

…fixed database adapter function errors and typos

2023-07-02 19:56 UTC, raynhlee approved these changes

2023-07-03 19:39 UTC, Kieren27 requested changes
I don't think we'll need the variable "myToken" to exist in the API, since the front-end is now initialized we can instead store the token after logging in / registering in a useState, and test the other features that way.

2023-07-05 00:20 UTC, MtKrc approved these changes

2023-07-05 00:55 UTC, Kieren27 approved these changes

2023-07-05 00:55 UTC, merged